use std::{fs::File, io::Read, path::PathBuf, time::Instant};

use clap::Parser;
use kraft::{
    evaluate,
    models::partition_dfa::{ByteHistory, PartitionDfa},
};

#[derive(Parser)]
#[command(
    about = "Causal exact posterior over emission partitions of a generated byte-history DFA"
)]
struct Args {
    path: PathBuf,
    #[arg(long, default_value_t = 100_000)]
    limit: u64,
    /// Maximum partition depth; defines the finite model prior.
    #[arg(long, default_value_t = 8)]
    depth: usize,
}

fn run(args: Args) -> Result<(), Box<dyn std::error::Error>> {
    let started = Instant::now();
    let mut model = PartitionDfa::new(ByteHistory::new(args.depth));
    let result = evaluate(File::open(args.path)?.take(args.limit), &mut model)?;
    println!(
        "bytes\tdepth\ttotal_nats\tbits_per_byte\tln_evidence\tnodes\tnode_updates\telapsed_s"
    );
    println!(
        "{}\t{}\t{:.9}\t{:.9}\t{:.9}\t{}\t{}\t{:.6}",
        result.bytes,
        args.depth,
        result.total_nats,
        result.total_bits() / result.bytes as f64,
        model.ln_evidence(),
        model.nodes(),
        model.node_updates(),
        started.elapsed().as_secs_f64()
    );
    Ok(())
}

pub fn command(args: Vec<std::ffi::OsString>) -> std::io::Result<()> {
    let argv = std::iter::once(std::ffi::OsString::from("kraft eval partition-dfa")).chain(args);
    let args = match Args::try_parse_from(argv) {
        Ok(args) => args,
        Err(error)
            if matches!(
                error.kind(),
                clap::error::ErrorKind::DisplayHelp | clap::error::ErrorKind::DisplayVersion
            ) =>
        {
            print!("{error}");
            return Ok(());
        }
        Err(error) => {
            return Err(std::io::Error::new(
                std::io::ErrorKind::InvalidInput,
                error.to_string(),
            ));
        }
    };
    run(args).map_err(|error| std::io::Error::other(error.to_string()))
}
